package rules


rule "rule_agendagroup_1"
    // 议程中的分组只有被设置了焦点才会触发
    // 可以设置多个焦点
    // 与 activation group 不同的是，议程可以触发焦点内的多个规则，activation group 只能触发一个规则
    agenda-group "myagendagroup_1"
    // 可以通过设置 auto-focus 设置默认焦点
    // auto-focus true
    when
    then
        System.out.println("规则rule_agendagroup_1触发");
end

rule "rule_agendagroup_2"
    agenda-group "myagendagroup_1"
    when
    then
        System.out.println("规则rule_agendagroup_2触发");
end

// -------------------------------

rule "rule_agendagroup_3"
    agenda-group "myagendagroup_2"
    when
    then
        System.out.println("规则rule_agendagroup_3触发");
end

rule "rule_agendagroup_4"
    agenda-group "myagendagroup_2"
    when
    then
        System.out.println("规则rule_agendagroup_4触发");
end