package rules

import io.github.coffee330501.droolsLearn.entity.Student

rule "rule_update"
when
     $s:Student(age < 10)
then
    $s.setAge($s.getAge() + 1);

    // 不使用update的话，不会更新到Fact对象中，只会修改源数据
    // 数据更新后所有规则都会重新匹配一遍，所有规则
    update($s);
    System.out.println("规则：年龄小于10触发，年龄+1，当前年龄" + $s.getAge() + "岁");
end

rule "rule_student_age大于等于10岁"
    when
        $s:Student(age >= 10)
    then
        System.out.println("规则rule_student_age大于10岁触发");
end